on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'go.*'
      - '**.go'
  push:
    branches:
      - 'main'
      - 'staging'
      - 'trying'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - name: 'go build'
        run: make build
      - name: 'go test'
        run: make test
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [build] # wait for build to lint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'latest'
          skip-go-installation: true
